#!/usr/bin/env python3
"""
Generate a valid map skeleton for the game's current map format.

Usage:
  python3 make_map.py <map_id> <width> <height> <output_folder>

Example:
  python3 make_map.py new_route 24 18 assets/data/maps

This creates:
  <output_folder>/<map_id>.map
"""

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a new .map file skeleton.")
    parser.add_argument("map_id", help="Map id and output file stem")
    parser.add_argument("width", type=int, help="Map width in tiles")
    parser.add_argument("height", type=int, help="Map height in tiles")
    parser.add_argument("output_folder", help="Folder to write the map file into")
    parser.add_argument(
        "--fill",
        default=".",
        help="Single tile character used to fill the [tiles] section. Default: '.'",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the output file if it already exists",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.width <= 0 or args.height <= 0:
        raise ValueError("width and height must be positive")
    if len(args.fill) != 1:
        raise ValueError("--fill must be a single character")
    if "|" in args.map_id or "@" in args.map_id:
        raise ValueError("map_id must not contain '|' or '@'")


def build_tiles(width: int, height: int, fill: str) -> str:
    row = fill * width
    return "\n".join(row for _ in range(height))


def build_map_contents(map_id: str, width: int, height: int, fill: str) -> str:
    tiles = build_tiles(width, height, fill)
    return f"""# {map_id}
# Generated by make_map.py

[header]
id|{map_id}
width|{width}
height|{height}

[tiles]
{tiles}

[warps]
# Format: fromX|fromY|targetMapId|targetX|targetY

[encounters]
# Format: speciesId|minLevel|maxLevel|weight

[npcs]
# Format: id|name|type|x|y|facing|sightRange|dialogue|sprite|party
# Dialogue stages separated by @@, each can have flag? prefix
"""


def main() -> None:
    args = parse_args()
    validate_args(args)

    output_dir = Path(args.output_folder)
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / f"{args.map_id}.map"
    if output_path.exists() and not args.force:
        raise FileExistsError(
            f"Refusing to overwrite existing file: {output_path} (use --force to overwrite)"
        )

    output_path.write_text(
        build_map_contents(args.map_id, args.width, args.height, args.fill), encoding="utf-8"
    )
    print(f"Created {output_path}")


if __name__ == "__main__":
    main()
